name: remote_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.17.0-0 <3.0.0"
dependencies:
  dio: ^5.3.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  fresh_dio: ^0.4.1
  hive_flutter: ^1.1.0

  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.1.1
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.1
  hive_generator: ^2.0.1
