name: local_storage
description: Dart package which manages local storage management
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.17.0-0 <3.0.0"
dependencies:
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  remote_repository:
    path: ../remote_repository

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.1
  hive_generator: ^2.0.1
